<a href="https://colab.research.google.com/github/AllanGonzales/LinearAlgebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***PRELIM EXAM ***


Question 1


In [7]:
import numpy as np
C= np.zeros((4,4))
np.fill_diagonal(C,1)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2


In [12]:
C= np.zeros((4,4))
np.fill_diagonal(C,1)
print ("C=")
print(C)

print("If doubled ")
print(2*c)

C=
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
If doubled 
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3

In [9]:
A= np.array ([2,7,4])
B= np.array ([3,9,8])
cross= np.cross(A,B)
print(cross)




[20 -4 -3]
